/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Blueprint export: turn a (possibly partial) ArchitecturalPlanResponse into
 * two downloadable, dependency-free artifacts:
 *
 *   1. scaffold.mjs   — a self-contained Node ESM script that materializes the
 *                       ENTIRE file tree + every boilerplate into a real repo.
 *                       Files are carried as a JSON object and written with
 *                       fs.writeFileSync, so arbitrary LLM-generated code
 *                       (template literals, `$`, backticks, quotes, newlines)
 *                       round-trips losslessly — no shell-escaping hazards.
 *
 *   2. BLUEPRINT.md   — the full human/agent-readable specification in one file.
 *
 * Everything here is pure (no React, no DOM) so it can be unit-tested directly.
 */

import { ArchitecturalPlanResponse } from "./types";

// ---------------------------------------------------------------------------
// 1. Collect every file the blueprint defines into ONE path -> content map.
//
// Five sources contribute files. `boilerplates` (the Coder's full tree) is
// CANONICAL: strategy artifacts (auth / test / CI-CD) only fill in paths the
// boilerplates didn't already cover, so a path is never written twice and the
// coder's complete-tree code is never clobbered by a narrower snippet.
// ---------------------------------------------------------------------------
export function collectFiles(plan: Partial<ArchitecturalPlanResponse>): Record<string, string> {
  const files: Record<string, string> = {};

  // Base layer: the Coder's boilerplates (canonical).
  if (plan.boilerplates) {
    for (const [path, content] of Object.entries(plan.boilerplates)) {
      if (path && typeof content === "string") files[path] = content;
    }
  }

  // Fill-in layer: only add when the path isn't already covered above.
  const addIfAbsent = (path?: string, content?: string) => {
    if (path && typeof content === "string" && !(path in files)) {
      files[path] = content;
    }
  };

  addIfAbsent(plan.authStrategy?.boilerplatePath, plan.authStrategy?.boilerplateCode);
  addIfAbsent(plan.testingStrategy?.configBoilerplatePath, plan.testingStrategy?.configBoilerplate);
  addIfAbsent(plan.testingStrategy?.sampleTestPath, plan.testingStrategy?.sampleTestCode);
  addIfAbsent(plan.cicdStrategy?.configFileTemplatePath, plan.cicdStrategy?.configFileContent);

  return files;
}

// Directories the tree declares explicitly — so intended *empty* dirs survive
// the scaffold even though no file forces their creation.
export function collectDirectories(plan: Partial<ArchitecturalPlanResponse>): string[] {
  if (!plan.tree) return [];
  return plan.tree
    .filter((n) => n.type === "directory" && typeof n.path === "string" && n.path.length > 0)
    .map((n) => n.path);
}

// ---------------------------------------------------------------------------
// 2. scaffold.mjs generator.
//
// The file map is embedded as a JSON object literal. JSON is a syntactic subset
// of a JS expression, so `const FILES = <JSON.stringify(...)>;` is valid JS and
// needs no escaping beyond what JSON.stringify already does.
// ---------------------------------------------------------------------------
export function buildScaffoldMjs(plan: Partial<ArchitecturalPlanResponse>): string {
  const files = collectFiles(plan);
  const dirs = collectDirectories(plan);
  const projectName = plan.projectName || "architecture-blueprint";

  const filesJson = JSON.stringify(files, null, 2);
  const dirsJson = JSON.stringify(dirs, null, 2);

  return `#!/usr/bin/env node
/**
 * Scaffold generated by Architect.OS for "${projectName.replace(/\*\//g, "* /")}".
 *
 * Usage:  node scaffold.mjs [target-dir]
 *         (target-dir defaults to the current directory)
 *
 * Writes every blueprint file to disk losslessly. Re-runnable; existing files
 * are overwritten with the blueprint version.
 */
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const FILES = ${filesJson};

const DIRS = ${dirsJson};

const root = resolve(process.argv[2] || ".");
console.log("Scaffolding into " + root + "\\n");

// Create explicitly-declared (possibly empty) directories first.
for (const dir of DIRS) {
  mkdirSync(join(root, dir), { recursive: true });
}

let written = 0;
let skipped = 0;
for (const [rel, content] of Object.entries(FILES)) {
  const abs = join(root, rel);
  if (existsSync(abs) && process.env.SCAFFOLD_NO_OVERWRITE === "1") {
    console.log("  = " + rel + " (exists, skipped)");
    skipped++;
    continue;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, "utf8");
  console.log("  + " + rel);
  written++;
}

console.log("\\nDone. " + written + " file(s) written" + (skipped ? ", " + skipped + " skipped" : "") + ".");
`;
}

// ---------------------------------------------------------------------------
// 3. BLUEPRINT.md generator.
//
// Code blocks are fenced with a backtick run LONGER than the longest run that
// appears inside the content, so embedded ``` fences can't terminate the block.
// ---------------------------------------------------------------------------
export function safeFence(content: string): string {
  let longest = 0;
  const runs = content.match(/`+/g);
  if (runs) {
    for (const r of runs) longest = Math.max(longest, r.length);
  }
  return "`".repeat(Math.max(3, longest + 1));
}

function codeBlock(content: string | undefined, lang = ""): string {
  if (!content) return "_(not provided)_\n";
  const f = safeFence(content);
  return `${f}${lang}\n${content}\n${f}\n`;
}

function bulletList(items: string[] | undefined): string {
  if (!items || items.length === 0) return "_(none)_\n";
  return items.map((i) => `- ${i}`).join("\n") + "\n";
}

export function buildBlueprintMarkdown(plan: Partial<ArchitecturalPlanResponse>): string {
  const out: string[] = [];
  const push = (s: string) => out.push(s);

  push(`# ${plan.projectName || "Architecture Blueprint"}\n`);
  if (plan.oneLiner) push(`> ${plan.oneLiner}\n`);
  push(`\n_Generated by Architect.OS._\n`);

  // Scope
  push(`\n## Requirements & Scope\n`);
  push(bulletList(plan.scope));

  // Stack
  if (plan.stack) {
    push(`\n## Technology Decision Matrix\n`);
    const s = plan.stack;
    const row = (label: string, d?: { name?: string; version?: string; reason?: string }) =>
      d ? `| ${label} | ${d.name ?? ""} ${d.version ? `(${d.version})` : ""} | ${(d.reason ?? "").replace(/\|/g, "\\|")} |` : "";
    push(`| Layer | Choice | Rationale |`);
    push(`| --- | --- | --- |`);
    push(row("Frontend", s.frontend));
    push(row("Backend", s.backend));
    push(row("Database", s.database));
    if (s.infraAndCaching) {
      push(`| Hosting | ${s.infraAndCaching.hosting ?? ""} | ${(s.infraAndCaching.reason ?? "").replace(/\|/g, "\\|")} |`);
      if (s.infraAndCaching.cacheOrQueue) push(`| Cache/Queue | ${s.infraAndCaching.cacheOrQueue} | — |`);
    }
    push("");
    if (s.database?.schemaPhilosophy) push(`\n**Schema philosophy:** ${s.database.schemaPhilosophy}\n`);
  }

  // Frontend guide
  if (plan.frontendGuide) {
    push(`\n## Frontend Strategy\n`);
    push(`**Styling library:** ${plan.frontendGuide.stylingLibrary ?? "—"}\n`);
    push(`\n**Performance:**\n`);
    push(bulletList(plan.frontendGuide.performanceTricks));
    push(`\n**Modular patterns:**\n`);
    push(bulletList(plan.frontendGuide.modularPatterns));
  }

  // File tree
  if (plan.tree && plan.tree.length > 0) {
    push(`\n## Directory Structure\n`);
    const treeText = plan.tree
      .map((n) => `${n.path}${n.type === "directory" ? "/" : ""}${n.shortLabel ? `   # ${n.shortLabel}` : ""}`)
      .join("\n");
    push(codeBlock(treeText));
  }

  // Boilerplates (every file)
  const files = collectFiles(plan);
  const filePaths = Object.keys(files);
  if (filePaths.length > 0) {
    push(`\n## File Boilerplates (${filePaths.length})\n`);
    for (const path of filePaths) {
      push(`\n### \`${path}\`\n`);
      push(codeBlock(files[path]));
    }
  }

  // Auth
  if (plan.authStrategy) {
    push(`\n## Authentication & Authorization\n`);
    push(`- **Method:** ${plan.authStrategy.method ?? "—"}`);
    push(`- **Password management:** ${plan.authStrategy.passwordManagement ?? "—"}`);
    push(`- **RBAC:** ${plan.authStrategy.rbac ?? "—"}\n`);
  }

  // Testing
  if (plan.testingStrategy) {
    push(`\n## Testing Strategy\n`);
    push(`- **Framework:** ${plan.testingStrategy.testingFramework ?? "—"}`);
    push(`- **Command:** \`${plan.testingStrategy.command ?? "—"}\`\n`);
  }

  // CI/CD
  if (plan.cicdStrategy) {
    push(`\n## CI/CD Pipeline — ${plan.cicdStrategy.toolName ?? ""}\n`);
    if (plan.cicdStrategy.reason) push(`${plan.cicdStrategy.reason}\n`);
    if (plan.cicdStrategy.stages) {
      push(`\n**Stages:**\n`);
      for (const stage of plan.cicdStrategy.stages) {
        push(`- **${stage.name}** — ${stage.description}`);
      }
      push("");
    }
  }

  // Agent execution plan
  if (plan.agentPlan) {
    push(`\n## Agent Execution Plan — ${plan.agentPlan.agentName ?? ""}\n`);
    push(`\n**Prerequisites:**\n`);
    push(bulletList(plan.agentPlan.setupPrerequisites));
    if (plan.agentPlan.phases) {
      push(`\n**Phases:**\n`);
      plan.agentPlan.phases.forEach((phase, i) => {
        push(`\n#### Phase ${i + 1}: ${phase.title}\n`);
        push(`${phase.description}\n`);
        if (phase.commandToRun) push(`\nRun: \`${phase.commandToRun}\`\n`);
        push(bulletList(phase.steps));
      });
    }
    push(`\n**Agent-specific tips:**\n`);
    push(bulletList(plan.agentPlan.agentSpecificTips));
  }

  push(`\n---\n`);
  push(`To scaffold this project, run \`node scaffold.mjs <target-dir>\` from the downloaded files.\n`);

  return out.join("\n");
}

// ---------------------------------------------------------------------------
// Browser-only helper: trigger a download for generated text. Guarded so the
// module stays importable (and testable) in a non-DOM Node context.
// ---------------------------------------------------------------------------
export function downloadText(filename: string, content: string, mime = "text/plain"): void {
  if (typeof document === "undefined" || typeof URL === "undefined") return;
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
